---
layout: essay
type: essay
title: "Asking the smart questions"
# All dates must be YYYY-MM-DD format!
date: 2024-01-25
published: true
labels:
  - SMART

---
## Be Smart
It is common for individuals to encounter setbacks during their problem-solving process and seek assistance, which is nothing to feel embarrassed about. Seeking help is a normal part of the learning process, and there are plenty of individuals willing to offer support. However, many overlook the importance of framing their questions effectively. Asking insightful questions is a valuable skill that many people struggle with. Miscommunication or poorly framed questions can quickly frustrate those offering assistance. While seeking pointers or addressing specific issues is generally acceptable, some individuals may over-rely on others to solve problems entirely on their behalf. To ask smart questions, individuals should first conduct their own research/troubleshooting and provide all relevant information upfront. Not everyone has the luxury of time to conduct extensive searches or engage in prolonged troubleshooting sessions, especially individuals such as software developers who dedicate significant time to their own projects. Simple inquiries that could be easily answered through independent research can consume valuable time better spent addressing pressing issues. A poorly articulated question not only wastes time but also hampers the problem-solving process. Developers, for instance, may need to request additional details to accurately pinpoint the root cause of an issue, diverting time from solving your issue. Effective communication and thoughtful inquiry facilitate smoother collaboration and ultimately lead to more efficient problem resolution.

## Think before you ask
Here is an example of a not so smart question: <a href="https://stackoverflow.com/questions/3047393/how-do-i-prevent-sql-injection-with-php-and-mysql?rq=3">This</a> user asked a question regarding how they are able to prevent SQL injection with PHP and MySQL. Additionally, they state that they have a form where user data is inputted but don't provide any code of what they stated. As expected, some users attempt to gain more information regarding his question, while others berate him for not searching first, as he would have found that his question has already been answered in a megathread. The question has many problems with regards to how to ask a smart question. The first is that the question is asked very vaguely and without much supporting information, leaving other users forced to fill in the blanks. Secondly, the issue that the poster brings up has already been solved in another question thread. He would have known that if he had first researched his problem before posting about it. Because this individual failed to provide additional details, they were unable to receive specific assistance. A well-constructed question involves clear communication, thorough research, and relevance to the topic, elements that were lacking in this inquiry.    
https://stackoverflow.com/questions/3047393/how-do-i-prevent-sql-injection-with-php-and-mysql?rq=3

## Clear, Consise and Thourough
<a href="https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0/40066889#40066889">Here</a> is an example of a smart question. This user asked about a problem he was facing: whenever he would sign a commit for Git, he would receive an error message stating, “error: gpg failed to sign the data fatal: failed to write commit object.” So he sought assistance from the community. He clearly stated what his problem was in a clear and concise manner. He then provided the remedies that he had already attempted along with their source links. By showing others that he had done his own research into finding a solution to his problem and had attempted solutions, he already showed them that their help could go towards someone eager for assistance and that their time wouldn't be wasted. Additionally, he provided the error logs to his commit and documented/updated any new possible solutions he had attempted. Because of this, many users provided a plethora of possible solutions which led to him finding the correct one and remedying his problem.

